### ISSUE TITLE
Normalized benchmark graphs on https://corecheck.dev/benchmarks ?

### ISSUE THREAD

**Issue by maflcko** [corecheck/corecheck#8]
Would it make sense to normalize each plotted line, to make it easier to spot outliers? Otherwise, with a liner axis, the largest benchmark (in time) will eclipse the smallest one (and their differences).

Proposed solution: Divide all data points for one line by the first data point of the line.

**Comment by aureleoules** [comment]
Thanks for the suggestion, I added a new widget on the [benchmarks page](https://corecheck.dev/benchmarks) for this.
I made the Y scale use log and highlight outliers. This is the best solution I found so far.
What do you think?
